#!/usr/bin/env bash
# Secure Atomic Red Team Installation Script
# Implements checksum verification and secure installation practices

set -euo pipefail

# Configuration
INSTALL_SCRIPT_URL="https://raw.githubusercontent.com/redcanaryco/invoke-atomicredteam/master/install-atomicredteam.ps1"
INSTALL_PATH="${HOME}/.local/powershell/Modules"
PROFILE_PATH="${HOME}/.config/powershell/Microsoft.PowerShell_profile.ps1"

# Expected SHA-256 checksum of the installation script
# IMPORTANT: Update this checksum when updating the upstream script
# To generate: curl -sL $INSTALL_SCRIPT_URL | sha256sum
EXPECTED_CHECKSUM="${ATOMIC_INSTALL_CHECKSUM:-VERIFY_ME}"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $*"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $*"; }
log_error() { echo -e "${RED}[ERROR]${NC} $*"; }

# Verify PowerShell is installed
if ! command -v pwsh &> /dev/null; then
    log_error "PowerShell (pwsh) is not installed"
    exit 1
fi

# Create temporary directory for download
TEMP_DIR=$(mktemp -d)
trap 'rm -rf "$TEMP_DIR"' EXIT

INSTALL_SCRIPT="${TEMP_DIR}/install-atomicredteam.ps1"

# Download installation script
log_info "Downloading Atomic Red Team installation script..."
if ! curl -fsSL -o "$INSTALL_SCRIPT" "$INSTALL_SCRIPT_URL"; then
    log_error "Failed to download installation script"
    exit 1
fi

# Verify checksum if provided
if [[ "$EXPECTED_CHECKSUM" != "VERIFY_ME" ]]; then
    log_info "Verifying checksum..."
    ACTUAL_CHECKSUM=$(sha256sum "$INSTALL_SCRIPT" | awk '{print $1}')

    if [[ "$ACTUAL_CHECKSUM" != "$EXPECTED_CHECKSUM" ]]; then
        log_error "Checksum verification failed!"
        log_error "Expected: $EXPECTED_CHECKSUM"
        log_error "Actual:   $ACTUAL_CHECKSUM"
        log_error "The installation script may have been tampered with."
        exit 1
    fi
    log_info "Checksum verified successfully"
else
    log_warn "Checksum verification skipped (ATOMIC_INSTALL_CHECKSUM not set)"
    log_warn "Actual checksum: $(sha256sum "$INSTALL_SCRIPT" | awk '{print $1}')"
    log_warn "Set ATOMIC_INSTALL_CHECKSUM environment variable for verification"
fi

# Create installation directory
log_info "Creating installation directory: $INSTALL_PATH"
mkdir -p "$INSTALL_PATH"

# Run installation with PowerShell
log_info "Running Atomic Red Team installation..."
pwsh -NoProfile -NonInteractive -Command "
    \$ErrorActionPreference = 'Stop'
    try {
        . '$INSTALL_SCRIPT'
        Install-AtomicRedTeam -InstallPath '$INSTALL_PATH' -Force
        Write-Host 'Installation completed successfully'
    } catch {
        Write-Error \"Installation failed: \$_\"
        exit 1
    }
"

# Create PowerShell profile
log_info "Creating PowerShell profile: $PROFILE_PATH"
mkdir -p "$(dirname "$PROFILE_PATH")"
cat > "$PROFILE_PATH" <<EOF
# Atomic Red Team PowerShell Profile
# Auto-generated by secure installation script

# Import Invoke-AtomicRedTeam module
Import-Module ${INSTALL_PATH}/invoke-atomicredteam/

# Set strict mode for better error detection
Set-StrictMode -Version Latest

# Execution policy (for awareness - may require adjustment)
# Get-ExecutionPolicy -List
EOF

# Verify installation
log_info "Verifying installation..."
if pwsh -NoProfile -NonInteractive -Command "Import-Module ${INSTALL_PATH}/invoke-atomicredteam/; Get-Command Invoke-AtomicTest" &> /dev/null; then
    log_info "Installation verified successfully"
else
    log_error "Installation verification failed"
    exit 1
fi

# List installed modules
log_info "Installed modules:"
ls -lh "$INSTALL_PATH"

log_info "PowerShell profile:"
cat "$PROFILE_PATH"

log_info "Installation complete!"
